### PR TITLE
Added More Things To My Card (Fixed Btns)

### PR DESCRIPTION
**Pull request by H644b**

### CODE REVIEW

**Comment by H644b** [comment]
Added a commit for replacing "Static" With Node.js

**Comment by appleflyerv3** [comment]
uhhhhhhhh are you actually dumb it doesnt use node.js

**Comment by H644b** [comment]
@appleflyerv3 *cough cough* 
Screenshot 2024-05-22 12 42 07 PM

**Comment by H644b** [comment]
Also even if it isnt node.js (Which it is) add my stuff to my card lol.

**Comment by appleflyerv3** [comment]
it downloads node doesnt mean it runs on node
anyways static page is ALSO correct

**Pull request closed without merging**
